### ISSUE TITLE
I need help - I'm newbie

### ISSUE THREAD

**Issue by nadbal07** [darkmatter2222/COD-MW-2019-DNN#5]
Hello!
I need some help to setting up DNN.

I installed everything, but when I want to start Run.py, it show me up some error.
(I opened CMD and write cd folder\EnemyDetector\Scripts\ then I write: python Run.py)

Thats the error:
https://prnt.sc/s6tk20
What I do wrong?
Please help me.

**Comment by nadbal07** [comment]
I think I found my problem, but not solution. I didn't download CODV7.h5 file, I don't know how to do it. I already downloaded git lfs, but I don't know what to do. Please, help me.

**Comment by OrbitalT** [comment]
@nadbal07 if your still interested in this project i have remade the .h5 file. [This Google Drive Link](https://drive.google.com/file/d/1_xOPdYpHkda_mh1SWyg9eFJKhAIix0Rq/view)

**Comment by darkmatter2222** [comment]
@OrbitalT , @nadbal07 ,

I have uploaded all latest models and all training/validation data, see readme (https://github.com/darkmatter2222/COD-MW-2019-DNN) 

Uploaded here:
https://www.kaggle.com/darkmatter2222/codmw2019dnnmodels
