### ISSUE TITLE
How to download modules?

### ISSUE THREAD

**Issue by nadbal07** [darkmatter2222/COD-MW-2019-DNN#7]
hello, how to download modules? v7

**Comment by YADJ123** [comment]
Hey there! Went to download the modules but it says too many requests. Is this something i have to do  via python using the kaggle module or? Thank you for your time.  EDIT:*Make an account* That easy. Thank you for all the hard work sir, also i envy your network and hardware setup :)

**Comment by darkmatter2222** [comment]
@YADJ123 ,

I just logged into Kaggle, and downloaded the models w/ no issues. Clicked the download link for each model and the whole package, both worked just fine for me. 

The error you are experiencing I do not recognize. Is that a google chrome error?  Screen Shot?

**Comment by YADJ123** [comment]
yeah its all good now, just waiting on tensorflow to update to python 3.9 atm
