### ISSUE TITLE
Error CODV4.h5

### ISSUE THREAD

**Issue by AnonymusKK** [darkmatter2222/COD-MW-2019-DNN#8]
When i try to start Run.py this pops up
No file or directory found at ..\Models\CODV4.h5

Have someone the link for the Model bc i saw only 2 Models that i downloaded.

Thank you

**Comment by darkmatter2222** [comment]
Use the V7 or V9 models here: https://www.kaggle.com/darkmatter2222/codmw2019dnnmodels

Download them and point to them.
